### ISSUE TITLE
Not working with new webapp update

### ISSUE THREAD

**Issue by KMAN8781** [oRastor/fut21-web-app#37] opened 2020-10-03 00:20 UTC
thanks for all the work you do!

there was a new webapp update today that added a new menu option titled "Stadium" along with some other minor things.
For some reason now, the bot isnt working very well. 

Can you look into fixing this?

I appreciate it

**Comment by Lqurens** [comment] 2020-10-03 17:01
the autobuyer tab now takes up the spot of the Stadium tab which makes the script to not work anymore

hope this gets updated asap

**Comment by TiebeVercoutter** [comment] 2020-10-03 17:30
Nothing has changed for me and everything still works. Can you show me a screenshot

**Comment by BzRk88** [comment] 2020-10-03 19:59
hi tiebe,

I just applied the update and now the searching goes to fast. how can i adjust that. i allready had 2 marketbans for an hour. hope it is easy to fix

**Comment by ruubmarges** [comment] 2020-10-03 20:15
![WhatsApp Image 2020-10-03 at 22 03 48](https://user-images.githubusercontent.com/72319981/95000972-df6b9d00-05c5-11eb-9215-c65f3bbfc806.jpeg)

I got the same problem...

**Comment by TiebeVercoutter** [comment] 2020-10-03 21:42
Oke the stadium thing is very weird since it is still working for me. When I turn tampermonkey off the stadium tab shows but when I turn te script back on and refresh the autobuyer tab shows again.

I will release an update that should fix the wait time issue. I also experienced soft bans but i never had a captcha which is weird because i got them a lot on fut20. Every year there will be bugs in the beginning so thanks for pointing them out!

The wait time standard will still be 2-5 but when you change it to x-y with x<y,  x and y  being a number it will now correctly change the wait time to be between x and y + a constant

**Comment by KMAN8781** [comment] 2020-10-03 21:47
I think a good option to add in (if possible) is the following:
A way to increase the max buy now by one click and then after the next search decrease it by one click.
That will the market will refresh more often

Example: 
First search - Maxbuynow = 1,500
Second search - Maxbuynow = 1,600
Third Search - Maxbuynow = 1,500
and so on

**Comment by TiebeVercoutter** [comment] 2020-10-03 22:00
I did a pull request for the fix Rastor now has to accept it.

Yes i agree with you but i think it is more a visual bug than a functional bug. New players still come up, but already bought players still show up for a few searches. You may not see it but the autobuyer is already changing maxbuynow behind the scenes. When i find the time i will try to see if there is some other way it can be implemented.

**Comment by ruubmarges** [comment] 2020-10-03 22:05
Is there something i could do to fix the buyer instead of the stadium? Tried to redownload it, but it didn't work.

**Comment by TiebeVercoutter** [comment] 2020-10-03 22:12
![image](https://user-images.githubusercontent.com/54238250/95002606-3aa58b80-05d6-11eb-8c39-0dd392654f13.png)

can you verify that you have this?

**Comment by ruubmarges** [comment] 2020-10-03 22:15
![Naamloos](https://user-images.githubusercontent.com/72319981/95002646-abe53e80-05d6-11eb-85e5-59344ef397dc.png)

**Comment by ruubmarges** [comment] 2020-10-03 22:18
Normally there would be a 2 there, but i don't know why it doenst work..

**Comment by TiebeVercoutter** [comment] 2020-10-03 22:19
And when opening the web app do you also see that they are active? There should be a 2 next to the tampermonkey chrome extension.

I have uploaded the files that i use on my profile page:

https://github.com/TiebeVercoutter/FIFA-21-Autobuyer

try using those 2 files and tell me if it is working.

**Comment by ruubmarges** [comment] 2020-10-03 22:23
When I click the files and click Raw, i can't add or download it. It will take me to a page with all the transcirpt.

**Comment by TiebeVercoutter** [comment] 2020-10-03 22:29
On the main page click code and then download as zip
or you can just copy the text of those to files and paste them in a tampermonkey file

**Comment by ruubmarges** [comment] 2020-10-03 22:33
![image](https://user-images.githubusercontent.com/72319981/95002874-2b740d00-05d9-11eb-86c0-d0f7d047b435.png)
 It still says version 1.2 when looking at the file.

**Comment by ruubmarges** [comment] 2020-10-03 22:35
Copied your files, still doens't work..

**Comment by TiebeVercoutter** [comment] 2020-10-03 22:38
What is not working are you now on 1.3?
Are you able to get on the web app?
Is the problem that you see the stadium tab?
Is your web app language set to English?

**Comment by ruubmarges** [comment] 2020-10-03 22:39
The files are now on 1.3 yes... I can get on the web app, and the problem is that I see the stadium Tab indeed. Yes the language is set to English.

**Comment by TiebeVercoutter** [comment] 2020-10-03 22:46
![image](https://user-images.githubusercontent.com/54238250/95003020-f668ba00-05da-11eb-95fd-b6e3a47ff1cb.png)

I don’t know what the problem is then I’m really sorry it is working for me.

**Comment by BzRk88** [comment] 2020-10-03 22:50
what is the best settings then to not get soft banned? Cause i am keep getting banned. On other accounts too

**Comment by TiebeVercoutter** [comment] 2020-10-03 22:57
There is not an “ideal” setting.

Is it realistic for a human to search every 30-40 second for 5 hours straight ? No it’s not. 

Find a good balance between speed and running time don’t let it run for too long and don’t set the wait time to low refresh from time to time and take some breaks in between that is the best advice I can give you .

**Comment by BzRk88** [comment] 2020-10-03 23:04
yeah i understand but before the update i wasnt searching so fast. I just want it to search slower. but everything i try doesnt work. it will keep searching each second, and sometimes with some pauses but not as it was before the update

**Comment by TiebeVercoutter** [comment] 2020-10-03 23:11
Well i did a pull request to fix that issue I don’t own this repo so i can only suggest the fix rastor will have to accept the change and then it will be fixed

If you go to the repo on my page and use the 1.3 files the fixes are already implemented

**Comment by BzRk88** [comment] 2020-10-03 23:14
you mean fixes for the searchtime? everything else is just fine

**Comment by TiebeVercoutter** [comment] 2020-10-03 23:20
Yes i made some changes to fix the wait time

**Comment by oRastor** [comment] 2020-10-04 04:15
PR was approved.

Merged two scripts into one. Added stadium menu item.
![screenshot-www ea com-2020 10 04-07_13_32](https://user-images.githubusercontent.com/1734394/95006835-38acee00-0611-11eb-8958-c1da7dfdbcb1.png)

**Comment by oRastor** [comment] 2020-10-04 04:23
You need to remove all scripts and install new one https://github.com/oRastor/fut21-web-app/blob/master/fut21-autobuyer.user.js

To install the script just click "raw" button. Then click "install" from tampermonkey interface.

**Comment by basgrootveld** [comment] 2020-10-04 06:32
Still doesn't work, i see the stadium instead the autobuyer icon

**Comment by basgrootveld** [comment] 2020-10-04 07:02
> Still doesn't work, i see the stadium instead the autobuyer icon

I also have only 1 script downloaded

**Comment by basgrootveld** [comment] 2020-10-04 07:13
The "2" in the right top corner just doesn't show anymore, i tried everything

**Comment by ruubmarges** [comment] 2020-10-04 08:08
I downloaded the new version. Still doens't work. When I load it up, it says there has been an issue attempting to save your latest changes...

**Comment by basgrootveld** [comment] 2020-10-04 08:10
> I downloaded the new version. Still doens't work. When I load it up, it says there has been an issue attempting to save your latest changes...
> 
> https://github.com/oRastor/fut21-web-app/issues/37#issuecomment-703173826

How many files have you installed because i only have 1 script now? It is not workung by me at all

**Comment by ruubmarges** [comment] 2020-10-04 08:11
> > I downloaded the new version. Still doens't work. When I load it up, it says there has been an issue attempting to save your latest changes...
> > [#37 (comment)](https://github.com/oRastor/fut21-web-app/issues/37#issuecomment-703173826)
> 
> How many files have you installed because i only have 1 script now? It is not workung by me at all

I have the latest one installed and the menu installment 1.3..

**Comment by basgrootveld** [comment] 2020-10-04 08:28
![image](https://user-images.githubusercontent.com/72332647/95010762-3c9a3980-062c-11eb-80b9-4a8c95a4ff98.jpeg)
![image](https://user-images.githubusercontent.com/72332647/95010763-3f952a00-062c-11eb-807f-ed5fd289b6c9.jpeg)
![image](https://user-images.githubusercontent.com/72332647/95010765-42901a80-062c-11eb-91c9-aedbb27a06f6.jpeg)

Nothing is working...

**Comment by TiebeVercoutter** [comment] 2020-10-04 08:32
Try and delete both those files and install just the one autobuyer file from this repo.

**Comment by basgrootveld** [comment] 2020-10-04 08:41
> Try and delete both those files and install just the one autobuyer file from this repo.

I did that now, i installed only that file but the problem is that it doesnt show in my menu
![image](https://user-images.githubusercontent.com/72332647/95011040-2beac300-062e-11eb-89ac-d41dad2cf67e.jpeg)

**Comment by TiebeVercoutter** [comment] 2020-10-04 08:58
It will only show running when you are on the web app

**Comment by basgrootveld** [comment] 2020-10-04 09:00
> It will only show running when you are on the web app

![image](https://user-images.githubusercontent.com/72332647/95011408-c51ad900-0630-11eb-8d39-1cb5b4b06d3f.jpeg)
Still not running

**Comment by aniuspms** [comment] 2020-10-04 09:51
who have problems need to log in from that link : https://www.ea.com/fifa/ultimate-team/web-app/ :)

**Comment by basgrootveld** [comment] 2020-10-04 10:30
> who have problems need to log in from that link : https://www.ea.com/fifa/ultimate-team/web-app/ :)

Yooooo  tysm!!!!

**Comment by basgrootveld** [comment] 2020-10-04 10:33
When i turn on the bot it gives me a "warning" in the log and it turns off?

**Comment by TiebeVercoutter** [comment] 2020-10-04 11:04
What settings are you using for the bot?
The bot automatically turns off when a search was not successful. Last year that happened when captcha verification was required. I haven’t had this issue yet but it could be a problem on the server side or your account

**Comment by BzRk88** [comment] 2020-10-04 19:32
Do you have the right url? Cause u had that problem before the update. And there was something with the url.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: basgrootveld <notifications@github.com>
Verzonden: Sunday, October 4, 2020 11:00:33 AM
Aan: oRastor/fut21-web-app <fut21-web-app@noreply.github.com>
CC: BzRk88 <hendriks_jimmy@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [oRastor/fut21-web-app] Not working with new webapp update (#37)


It will only show running when you are on the web app

[image]<https://user-images.githubusercontent.com/72332647/95011408-c51ad900-0630-11eb-8d39-1cb5b4b06d3f.jpeg>
Still not running

**Closed** 2020-10-05 21:20 UTC
